### ISSUE TITLE
Decrypted err: wrong tag: nested asn1 error: nested asn1 error: Field=n, Type=RSA: RSA lib: data greater than mod len

### ISSUE THREAD

**Issue by Elven-coder** [spacewander/lua-resty-rsa#51] opened 2022-06-09 02:23 UTC
I got the error message when I decrypted data encrypted by java.
How should I modify the lua scripts.

**Comment by spacewander** [comment] 2022-06-09 06:06
Duplicate of #50

**Closed as completed by spacewander** 2022-06-09 06:06 UTC
